### ISSUE TITLE
Pipe not found with audacity 3.0

### ISSUE THREAD

**Issue by samytichadou** [tin2tin/audacity_tools_for_blender#19]
Something seems to have changed in the in out pipe files from audacity 3.0 (at least on windows), unable to find the pipe now.

**Comment by tin2tin** [comment]
I did have it running on 3.0 earlier today. Let me check.

**Comment by tin2tin** [comment]
I can send from Blender to Audacity, it that's what you mean?

I have this pop-up showing that it is playing in Audacity, and it is not reacting to the Blender stop command.

**Comment by samytichadou** [comment]
nop, i can't get the pipe here 

![image](https://user-images.githubusercontent.com/26276003/111650897-09c4b600-8806-11eb-8984-12da8a3ef000.png)

Unable to send/receive anything because of this

**Comment by tin2tin** [comment]
I guess, when I got all of those bugs I mentioned to you, I must have been running a 3.0 beta version. I hope they can find a solution in Audacity, so our efforts will not be in wain. Keep an eye on that link about. They might come up with a solution for us.

**Comment by tin2tin** [comment]
The loop vs. pop up problem has been fixed in the github actions builds: https://github.com/audacity/audacity/actions/workflows/cmake_build.yml

James from Audacity asks if piping works in 3.0 if, after enabling the pipe, audacity is restarted?

**Comment by samytichadou** [comment]
> James from Audacity asks if piping works in 3.0 if, after enabling the pipe, audacity is restarted?

Nop, not for me at least on windows. I can't really enable the pipe, even if audacity is opened when blender launches, restarted... No luck for now

**Comment by tin2tin** [comment]
Hmm... not good. The weird thing is that it is working for me. I'm using 2.93 master and Audacity 3.0 bleeding edge. 

Maybe you could explain it a bit more in that forum thread, and maybe they can help you troubleshoot it, so the cause of this can be found? https://forum.audacityteam.org/viewtopic.php?f=70&t=116650 (it's a bit hard for me to do, since currently I'm not able to reproduce it)

Oh, an idea, could it be something with write permissions? Like the location of Audacity(have you tried a portable version)? Or do you need to run Blender as admin? Or try to delete all audacity temp files in the roaming folder?

**Comment by samytichadou** [comment]
uploading to 2.92 (i still was in 2.91.2) for blender version and reinstalling everything seems to have fixed the problem...
Maybe something i did wrong previously, or missed. But seems to works fine with audacity 3.0 now ! 
Closing this issue

**Comment by tin2tin** [comment]
Strange, but yes, I had the same problems at one point.  Glad you solved it.
